/* Copyright Homeaway, Inc 2005-2008. All Rights Reserved.
 * No unauthorized use of this software.
 */
package org.atomserver.perf;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.atomserver.testutils.perf.TimedTestCase;

/**
 * Basic performance test suite.
 */
public class PerfTestSuite extends TestCase {

    // Note that each method will be run as a single unit of test, so the expected timing
    // should include setup and teardown time.

    // Following list includes all the currently existing JUnit tests with estimated maximum timing for each test.
    // The maximum time may vary based on the system environment, database used, etc.
    
    static private TestCase[] initTestList() {
        
         return new TestCase[] {
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testGetServiceDocument",4200),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testReadFeed",3327),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testReadUpdatedFeed",3990),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testCreateEntry",3405),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testCreateAndReadEntry",3693),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testDeleteEntry",3444),
            new TimedTestCase(org.atomserver.blogs.BlogServiceTest.class,"testUpdateEntry",3717),
            new TimedTestCase(org.atomserver.core.EntryURIHelperTest.class,"testError",3500),
            new TimedTestCase(org.atomserver.core.EntryURIHelperTest.class,"testDate",360),
            new TimedTestCase(org.atomserver.core.EntryURIHelperTest.class,"testDate2",825),
            new TimedTestCase(org.atomserver.core.EntryURIHelperTest.class,"testSuccess",465),
            new TimedTestCase(org.atomserver.core.EntryURIHelperTest.class,"testMissingId",354),
            new TimedTestCase(org.atomserver.core.ExtendedContextCustomEnvTest.class,"testExtendedContext",1386),
            new TimedTestCase(org.atomserver.core.ExtendedContextOpsDirTest.class,"testExtendedContext",759),
            new TimedTestCase(org.atomserver.core.ExtendedContextTest.class,"testExtendedContext",1365),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testPhysicalStorage",10083),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testFaultyStorage",500),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testStorageErrors",6768),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testTrashDir",12045),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testLagTime",6024),
            new TimedTestCase(org.atomserver.core.PhysicalStorageTest.class,"testZeroRev",1000),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testCollectionUpdateMinMax",534),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testCollectionEntryType",387),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testCollectionMaxResults",396),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testEntryUpdatedMaxMin",453),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testCollectionStartEndIndex",831),
            new TimedTestCase(org.atomserver.core.QueryParamTest.class,"testEntryStartEndIndex",429),
            new TimedTestCase(org.atomserver.core.RegexTargetResolverTest.class,"testCollection",780),
            new TimedTestCase(org.atomserver.core.RegexTargetResolverTest.class,"testService",456),
            new TimedTestCase(org.atomserver.core.RegexTargetResolverTest.class,"testEntry",444),
            new TimedTestCase(org.atomserver.core.URIHandlerTest.class,"testIRIParsing",21),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsDBSTest.class,"testAggregateFeeds",44493),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsLocaleTest.class,"testLocaleInAggFeeds",19938),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsLocaleTest.class,"testLocaleInAggFeeds2",19821),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsTest.class,"testAggregateFeeds",140034),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsTest.class,"testStartEndIndex",30399),
            new TimedTestCase(org.atomserver.core.dbstore.AggregateFeedsTest.class,"testUpdateMaxMin",51330),
            new TimedTestCase(org.atomserver.core.dbstore.AutoTaggingDBSTest.class,"testXPathAutoTagging",1902),
            new TimedTestCase(org.atomserver.core.dbstore.AutoTaggingDBSTest.class,"testTooLarge",933),
            new TimedTestCase(org.atomserver.core.dbstore.AutoTaggingDBSTest.class,"testEmptyTerm",1326),
            new TimedTestCase(org.atomserver.core.dbstore.AutoTaggingDBSTest.class,"testDeleteEmptyTerm",1188),
            new TimedTestCase(org.atomserver.core.dbstore.BatchDBSTest.class,"testAll",12561),
            new TimedTestCase(org.atomserver.core.dbstore.CRUDDBSTest.class,"testCRUD",6000),
            new TimedTestCase(org.atomserver.core.dbstore.CRUDDBSTest.class,"testDeleteNonExistent",1101),
            new TimedTestCase(org.atomserver.core.dbstore.CRUDDBSTest.class,"testMultipleDeletions",1644),
            new TimedTestCase(org.atomserver.core.dbstore.ClearDBSTest.class,"testClearDB",1200),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentBatchDBSTest.class,"testAll",12084),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentCRUDDBSTest.class,"testCRUD",1476),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentCRUDDBSTest.class,"testDeleteNonExistent",993),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentCRUDDBSTest.class,"testMultipleDeletions",1581),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentEntryDBSTest.class,"testVarious",35940),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentFeedDBSTest.class,"testSeveralScenarios",61542),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentNonLocalizedEntriesDBSTest.class,"testNonLocalized",15807),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentPostDBSTest.class,"testCRUDNoLocale",1752),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentPostDBSTest.class,"testCRUDWithLocale",1500),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentPostDBSTest.class,"testMinimalEntry",1689),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentRevisionDBSTest.class,"testCRUD",1752),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsBasicsDBSTest.class,"testGetServiceDocument",17769),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsBasicsDBSTest.class,"testTooLarge",17073),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsBasicsDBSTest.class,"testFeedWithCategories",16452),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsBasicsDBSTest.class,"testEntryWithCategories",16899),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsFeedEntriesCategoriesDBSTest.class,"testFeedWithOneCategory",61677),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsFeedQueriesDBSTest.class,"testFeedWithOneCategory",59667),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsFeedQueriesDBSTest.class,"testFeedWithMultipleCategories",111777),
            new TimedTestCase(org.atomserver.core.dbstore.DBContentTagsFeedQueriesDBSTest.class,"testRaceConditionWritingNewTagsWorkspace",23130),
            new TimedTestCase(org.atomserver.core.dbstore.DelegatingProviderTest.class,"testCRUD",3003),
            new TimedTestCase(org.atomserver.core.dbstore.EndIndexParamDBSTest.class,"testEndIndex",25584),
            new TimedTestCase(org.atomserver.core.dbstore.EnforcedLatencyTest.class,"testRaceCondition",106698),
            new TimedTestCase(org.atomserver.core.dbstore.EntryDBSTest.class,"testVarious",36573),
            new TimedTestCase(org.atomserver.core.dbstore.EntryTypeParamDBSTest.class,"testVarious",25000),
            new TimedTestCase(org.atomserver.core.dbstore.ErrorsDBSTest.class,"testErrorHandling",25000),
            new TimedTestCase(org.atomserver.core.dbstore.ErrorsDBSTest.class,"testBadUpdate",20000),
            new TimedTestCase(org.atomserver.core.dbstore.ErrorsDBSTest.class,"testBadDelete",20000),
            new TimedTestCase(org.atomserver.core.dbstore.FailDBSTest.class,"testNullXML",15000),
            new TimedTestCase(org.atomserver.core.dbstore.FailDBSTest.class,"testEmptyXML",1000),
            new TimedTestCase(org.atomserver.core.dbstore.FailDBSTest.class,"test500ErrorLogs",1000),
            new TimedTestCase(org.atomserver.core.dbstore.FeedDBSTest.class,"testSeveralScenarios",66000),
            new TimedTestCase(org.atomserver.core.dbstore.FileRetryDBSTest.class,"testFileRetry",9500),
            new TimedTestCase(org.atomserver.core.dbstore.FileRetryDBSTest.class,"testFileRetry2",12000),
            new TimedTestCase(org.atomserver.core.dbstore.FileRetryDBSTest.class,"testFileRetry3",7000),
            new TimedTestCase(org.atomserver.core.dbstore.FileRetryDBSTest.class,"testFileRetry4",9000),
            new TimedTestCase(org.atomserver.core.dbstore.GzipAndShardingMigrationTest.class,"testGzipAndShardingMigration",70000),
            new TimedTestCase(org.atomserver.core.dbstore.InOutDBSTest.class,"testInOut",20000),
            new TimedTestCase(org.atomserver.core.dbstore.InfoqAggExampleTest.class,"testAggregateFeeds",35000),
            new TimedTestCase(org.atomserver.core.dbstore.KeepaliveDBSTest.class,"testKeepalives",17000),
            new TimedTestCase(org.atomserver.core.dbstore.MTEntryDBSTest.class,"testHittingAllDifferentOnes",70000),
            new TimedTestCase(org.atomserver.core.dbstore.LocaleParamDBSTest.class,"testSeveralScenarios",35000),
            new TimedTestCase(org.atomserver.core.dbstore.MTEntryDBSTest.class,"testHittingTheSameOne",25000),
            new TimedTestCase(org.atomserver.core.dbstore.MTFeedDBSTest.class,"testMultiThreadedFeedReads",70000),
            new TimedTestCase(org.atomserver.core.dbstore.MTFeedDBSTest.class,"testWriteContention",45000),
            new TimedTestCase(org.atomserver.core.dbstore.MTMixedDBSTest.class,"testmixedLoad",90000),
            new TimedTestCase(org.atomserver.core.dbstore.NoDirDBSTest.class,"testNoDir",45000),
            new TimedTestCase(org.atomserver.core.dbstore.NonLocalizedEntriesDBSTest.class,"testNonLocalized",16500),
            new TimedTestCase(org.atomserver.core.dbstore.ObliterateTest.class,"testObliterate",17000),
            new TimedTestCase(org.atomserver.core.dbstore.OptConcDBSTest.class,"testInsertNonZeroRev",1000),
            new TimedTestCase(org.atomserver.core.dbstore.OptConcDBSTest.class,"testInsertZeroRev",2000),
            new TimedTestCase(org.atomserver.core.dbstore.OptConcDBSTest.class,"testInsertNoRev",1000),
            new TimedTestCase(org.atomserver.core.dbstore.OptConcDBSTest.class,"testInsertAnyRev",1200),
            new TimedTestCase(org.atomserver.core.dbstore.PostDBSTest.class,"testCRUDNoLocale",3000),
            new TimedTestCase(org.atomserver.core.dbstore.PostDBSTest.class,"testCRUDWithLocale",2500),
            new TimedTestCase(org.atomserver.core.dbstore.PostDBSTest.class,"testMinimalEntry",1500),
            new TimedTestCase(org.atomserver.core.dbstore.RawClientDBSTest.class,"testMissingEntryContent",1200),
            new TimedTestCase(org.atomserver.core.dbstore.RawClientDBSTest.class,"testMissingEntryContent2",1500),
            new TimedTestCase(org.atomserver.core.dbstore.RawClientDBSTest.class,"testEmptyRequest",1200),
            new TimedTestCase(org.atomserver.core.dbstore.RawClientDBSTest.class,"testNoNamespace",1500),
            new TimedTestCase(org.atomserver.core.dbstore.RelaxNGValidatingDBSTest.class,"testListing",2000),
            new TimedTestCase(org.atomserver.core.dbstore.RevisionDBSTest.class,"testCRUD",1600),
            new TimedTestCase(org.atomserver.core.dbstore.StringIdCRUDDBSTest.class,"testCRUD",2200),
            new TimedTestCase(org.atomserver.core.dbstore.TagsBasicsDBSTest.class,"testGetServiceDocument",5800),
            new TimedTestCase(org.atomserver.core.dbstore.TagsBasicsDBSTest.class,"testTooLarge",5500),
            new TimedTestCase(org.atomserver.core.dbstore.TagsBasicsDBSTest.class,"testFeedWithCategories",17500),
            new TimedTestCase(org.atomserver.core.dbstore.TagsBasicsDBSTest.class,"testEntryWithCategories",17000),
            new TimedTestCase(org.atomserver.core.dbstore.TagsCRUDDBSTest.class,"testCRUD",1500),
            new TimedTestCase(org.atomserver.core.dbstore.TagsFeedEntriesCategoriesDBSTest.class,"testFeedWithOneCategory",64000),
            new TimedTestCase(org.atomserver.core.dbstore.TagsFeedQueriesDBSTest.class,"testFeedWithOneCategory",62000),
            new TimedTestCase(org.atomserver.core.dbstore.TagsFeedQueriesDBSTest.class,"testFeedWithMultipleCategories",115000),
            new TimedTestCase(org.atomserver.core.dbstore.TagsFeedQueriesDBSTest.class,"testRaceConditionWritingNewTagsWorkspace",24000),
            new TimedTestCase(org.atomserver.core.dbstore.TagsLogEventDBSTest.class,"testEntryWithCategories",17000),
            new TimedTestCase(org.atomserver.core.dbstore.TxnDBSTest.class,"testTxn",2400),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMaxParamDBSTest.class,"testReadFeed",48000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMaxParamDBSTest.class,"testBadDate",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMaxParamDBSTest.class,"testMaxBeforeMin",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMaxParamDBSTest.class,"testReadEntry",26000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testBadDate",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testReadFeedSinceEmpty",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testWithTimeZonePlus",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testWithFutureTime",26000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testReadFeedSince",32000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testGetEntrySincePasses",25000),
            new TimedTestCase(org.atomserver.core.dbstore.UpdatedMinParamDBSTest.class,"testGetEntrySinceFails",25000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.BatchEntriesDAOTest.class,"testSelectBatch",2500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.BatchEntriesDAOTest.class,"testCRUDBatch",2500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.CategoryPagingEntriesDAOTest.class,"testPageWithCategories",17000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.ContentDAOTest.class,"testContentDAO",800),
            new TimedTestCase(org.atomserver.core.dbstore.dao.ContentDAOTest.class,"testDeleteAll1",630),
            new TimedTestCase(org.atomserver.core.dbstore.dao.ContentDAOTest.class,"testDeleteAll2",1100),
            new TimedTestCase(org.atomserver.core.dbstore.dao.ContentDAOTest.class,"testDeleteAll3",600),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testCRUD",11000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testSysDate",570),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testSelectEntryByLocale",700),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testSelectEntryByLocaleWithLotsPresent",3800),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testSort",8000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntriesDAOTest.class,"testDeleteAll",8500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoriesDAOTest.class,"testCRUD",1500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoriesDAOTest.class,"testSelectDistictCategoriesPerCollection",1600),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoriesDAOTest.class,"testSelectDistinctCollections",1500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoriesDAOTest.class,"testBatch",1500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoriesDAOTest.class,"testSelectEntryCategories",2000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.LocaleEntriesDAOTest.class,"testPageWithLocales",8000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.PageEntriesDAOTest.class,"testPage",7000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.PageEntriesDAOTest.class,"testPage2",16000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.TransactionTest.class,"testTransactionalBehavior",650),
            new TimedTestCase(org.atomserver.core.dbstore.utils.PurgeDBSTest.class,"testPurger",50000),
            new TimedTestCase(org.atomserver.core.dbstore.utils.SeederDBSTest.class,"testSeedDB",16000),
            new TimedTestCase(org.atomserver.core.filestore.CRUDFSTest.class,"testNothing",1200),
            new TimedTestCase(org.atomserver.core.filestore.ErrorsFSTest.class,"testErrorHandling",23000),
            new TimedTestCase(org.atomserver.core.filestore.ErrorsFSTest.class,"testBadRootDir",17000),
            new TimedTestCase(org.atomserver.core.filestore.ErrorsFSTest.class,"testNFSFailure",18000),
            new TimedTestCase(org.atomserver.core.filestore.FilestoreTest.class,"testNothing",1300),
            new TimedTestCase(org.atomserver.core.validators.RelaxNGContentValidatorTest.class,"testSimpleSchema",50),
            new TimedTestCase(org.atomserver.core.validators.RelaxNGContentValidatorTest.class,"testWidgetSchema",150),
            new TimedTestCase(org.atomserver.core.validators.SimpleXMLContentValidatorTest.class,"testValidate",50),
            new TimedTestCase(org.atomserver.exceptions.BadContentExceptionTest.class,"testException",50),
            new TimedTestCase(org.atomserver.exceptions.BadRequestExceptionTest.class,"testException",50),
            new TimedTestCase(org.atomserver.exceptions.EntryNotFoundExceptionTest.class,"testException",50),
            new TimedTestCase(org.atomserver.exceptions.MovedPermanentlyExceptionTest.class,"testException",50),
            new TimedTestCase(org.atomserver.exceptions.OptimisticConcurrencyExceptionTest.class,"testException",60),
            new TimedTestCase(org.atomserver.testutils.log.Log4jHelperTest.class,"testSetAppLogLevel",60),
            new TimedTestCase(org.atomserver.testutils.log.Log4jHelperTest.class,"testSetRootLogLevel",60),
            new TimedTestCase(org.atomserver.testutils.log.Log4jHelperTest.class,"testSetArbitraryLogLevel",60),
            new TimedTestCase(org.atomserver.testutils.plot.PerfDataSetTest.class,"test1",150),
            new TimedTestCase(org.atomserver.testutils.plot.PlotTest.class,"testPlotCombined",1900),
            new TimedTestCase(org.atomserver.testutils.plot.PlotTest.class,"testPlotAll",1000),
            new TimedTestCase(org.atomserver.utils.PartitionPathGeneratorsTest.class,"testPrefixPartitionPathGenerator",100),
            new TimedTestCase(org.atomserver.utils.PartitionPathGeneratorsTest.class,"testShardedPartitionPathGenerator",100),
            new TimedTestCase(org.atomserver.utils.ShardedPathTest.class,"testShardedPath",100),
            new TimedTestCase(org.atomserver.utils.WoodstoxTest.class,"testWoodstox1",100),
            new TimedTestCase(org.atomserver.utils.WoodstoxTest.class,"testWoodstox2",4000),
            new TimedTestCase(org.atomserver.utils.acegi.RESTfulDefinitionSourceTest.class,"testBasics",50),
            new TimedTestCase(org.atomserver.utils.acegi.RESTfulDefinitionSourceTest.class,"testFail",50),
            new TimedTestCase(org.atomserver.utils.acegi.RESTfulDefinitionSourceTest.class,"testNoMatch",50),
            new TimedTestCase(org.atomserver.utils.alive.AliveServletTest.class,"testSuccess",3000),
            new TimedTestCase(org.atomserver.utils.alive.AliveServletTest.class,"testInitialState",1500),
            new TimedTestCase(org.atomserver.utils.alive.AliveServletTest.class,"testFileSystemFailure",1500),
            new TimedTestCase(org.atomserver.utils.alive.AliveServletTest.class,"testDBFailure",1000),
            new TimedTestCase(org.atomserver.utils.alive.AliveServletTest.class,"testTTL",6000),
            new TimedTestCase(org.atomserver.utils.collections.BidirectionalMapTest.class,"testReverseGet",50),
            new TimedTestCase(org.atomserver.utils.io.JarUtilsTest.class,"test2",50),
            new TimedTestCase(org.atomserver.utils.io.JarUtilsTest.class,"test1",50),
            new TimedTestCase(org.atomserver.utils.locale.LocaleUtilsTest.class,"test1",7000),
            new TimedTestCase(org.atomserver.utils.logic.BooleanLogicTest.class,"testBooleanLogic",50),
            new TimedTestCase(org.atomserver.utils.test.TestingAtomServerTest.class,"testSpringConfigured",8000),
            new TimedTestCase(org.atomserver.utils.test.TestingAtomServerTest.class,"testAPIConfigured",7500),
            new TimedTestCase(org.atomserver.utils.xml.XMLTest.class,"testXMLGenerator",50),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoryLogEventDAOTest.class,"testCRUD",2500),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoryLogEventDAOTest.class,"testBatch",2000),
            new TimedTestCase(org.atomserver.core.dbstore.dao.EntryCategoryLogEventDAOTest.class,"testSelect",2000),
        };
    }

    public static Test suite() {

        TestCase[] testCases = initTestList();
        
        TestSuite perfSuite = new TestSuite();

        for (TestCase testCase : testCases) {
            perfSuite.addTest(testCase);
        }
        return perfSuite;
    }

}
